name: Generate README Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: DenverCoder1/github-readme-stats@v1
        with:
          username: TharunG2006
          theme: tokyonight
          show_icons: true
          output: profile-stats.svg

      - name: Generate Top Languages Card
        uses: DenverCoder1/github-readme-stats@v1
        with:
          username: TharunG2006
          layout: compact
          theme: tokyonight
          output: top-langs.svg

      - name: Commit Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.svg
          git commit -m "Update README stats" || exit 0
          git push
