name: Update README Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          username: TharunG2006
          show_icons: true
          theme: tokyonight
          output_path: profile-stats.svg

      - name: Generate Top Languages SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          username: TharunG2006
          layout: compact
          theme: tokyonight
          output_path: top-langs.svg

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.svg
          git commit -m "Update README stats" || exit 0
          git push
